# .github/configs/label-commenter-config.yml

labels:
  - name: '审核中'
    labeled:
      issue:
        body: |
          **👏 感谢您的支持，接下来请等待审核！**
          
          您已经完成了友链申请，由于博主设置了友链申请条件，接下来博主将会等待条件满足后完成审批。
  
  - name: '审核失败'
    labeled:
      issue:
        body: |
          **😦 有些条件还不满足呢，稍后再来吧**

          > 建议你重新看一下申请说明~
 
  - name: '审核通过'
    labeled:
      issue:
        body: |
          **🎉 恭喜，友链添加成功！**

          稍后片刻刷新 [网页](https://watermelonabc.top/friends/) 就可以看到您的链接。

          > 如果您的站点信息发生了变动，请直接修改这个 issue 的内容。

  - name: '失联'
    labeled:
      issue:
        action: close
        body: |
          **⚠️ 抱歉，您的网站长期打不开，现已暂时下架。**

          如果您确认可以打开，请在下方评论告知，我们会在人工审核通过后恢复上架。
