name: 友链模板
description: 自助添加友链。
labels: ['审核中']
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 检查清单
      description: 请认真检查以下清单中的每一项，并在相符的项前打勾。（在满足所有条件后才会通过，不满足的项请不要勾选）
      options:
        - required: true
          label: 合法、非营利性、无商业广告、无木马植入。
        - required: false
          label: 有原创内容的 HTTPS 站点，发布过至少 5 篇文章，内容题材不限。
  - type: textarea
    id: json-data
    validations:
      required: true
    attributes:
      label: 友链信息
      description: |
        请在下方的 `JSON` 块的双引号中填写，不要修改格式。
        | 字段        | 说明                |
        | ----------  | ------------------ |
        | title       | 友链标题           |
        | url         | 友链地址           |
        | icon        | 网站图标（如要设置，请删除占位图标URL）          |
        | description | 一句话简介【可选】  |
        | screenshot  | 网站截图【可选】    |
        | feed        | 订阅地址（用于抓取最新文章）【可选】    |
      value: |
        ```json
        {
            "title": "",
            "url": "",
            "icon": "https://blog.watermelonabc.top/assets/icon/solar-cat.svg",
            "screenshot": "",
            "description": "",
            "feed": ""
        }
        ```
  - type: input
    id: friends-html
    attributes:
      label: 友链展示地址（可选）
      description: 请输入您的友链展示页面地址。如无，可以输入主页或其他页面地址。
      placeholder: "如: https://blog.watermelonabc.top/friends"
  - type: input
    id: friends-repo
    attributes:
      label: 自助友链地址（可选）
      description: 如果您使用自助友链，可附上申请链接。博主将会前往您指定的网站自行填写友链。
      placeholder: "如: https://github.com/rt265/Blog-Friends"
